using System.Collections.Generic;
using System.IO;
using System.Text;

namespace AstroModIntegrator
{
    public static class ModIntegrator
    {
        public static string LastUpdated = "1.13.129.0";

        public static void IntegrateMods(string folderPath) // @"C:\Users\Alexandros\AppData\Local\Astro\Saved\Paks"
        {
            Directory.CreateDirectory(folderPath);
            string[] files = Directory.GetFiles(folderPath, "*_P.pak", SearchOption.TopDirectoryOnly);

            List<string> newComponents = new List<string>();
            foreach (string file in files)
            {
                Metadata us = MetadataExtractor.Read(file);
                if (us == null) continue;
                string[] theseComponents = us.linked_actor_components;
                if (theseComponents == null) continue;
                newComponents.AddRange(theseComponents);
            }

            string decidedNewMetadata = "{\"name\":\"AstroModLoader Mod Integrator\",\"author\":\"\",\"description\":\"Pak file auto-generated by AstroModLoader.\",\"version\":\"0.1.0\",\"astro_build\":\"" + LastUpdated + "\",\"sync\":\"serverclient\"}";

            var pciBaker = new PlayControllerInstanceBaker();
            byte[] pciData = pciBaker.Bake(newComponents.ToArray()).ToArray();
            byte[] pakData = PakBaker.Bake(new Dictionary<string, byte[]>
            {
                { "Astro/Content/Globals/PlayControllerInstance.uasset", pciData},
                { "metadata.json", Encoding.UTF8.GetBytes(decidedNewMetadata) }
            });

            using (FileStream f = new FileStream(Path.Combine(folderPath, @"999-AstroModLoader_P.pak"), FileMode.Create, FileAccess.Write))
            {
                f.Write(pakData, 0, pakData.Length);
            }
        }
    }
}
